[package]
name = "nina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.61"
eyre = "0.6.12"
hashbrown = "0.14.5"
